// Fragment geometry collection for destructible objects.
// Stores pre-baked fragment layout from Blender Cell Fracture.
// Reusable across different destructible object types.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "FlecsDestructibleGeometry.generated.h"

class UFlecsEntityDefinition;

/**
 * One fragment piece in the destructible layout.
 * Baked from Blender Cell Fracture — each piece has its mesh and relative position.
 */
USTRUCT(BlueprintType)
struct FDestructibleFragment
{
	GENERATED_BODY()

	/** Fragment mesh */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fragment")
	TObjectPtr<UStaticMesh> Mesh;

	/** Position/rotation relative to object center (from Blender export) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fragment")
	FTransform RelativeTransform;

	/** Optional: override DefaultFragmentDefinition for this specific fragment.
	 *  E.g., a glowing core piece with different Niagara/Damage profile.
	 *  nullptr = use DefaultFragmentDefinition from DestructibleProfile. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fragment")
	TObjectPtr<UFlecsEntityDefinition> OverrideDefinition;

	/** Box collider half-extents (cm). Auto-generated from mesh bounds via
	 *  GenerateColliderBounds(), manually editable for per-fragment tuning.
	 *  TODO: Support convex hull and other collider shapes for better fragment fit. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Collider")
	FVector ColliderHalfExtents = FVector(25.f);
};

/**
 * Adjacency link between two fragments — determines where constraints are placed.
 * Auto-generated by GenerateAdjacencyFromProximity() based on bounding box overlap.
 */
USTRUCT(BlueprintType)
struct FFragmentAdjacency
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int32 FragmentIndexA = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int32 FragmentIndexB = 0;
};

/**
 * Fragment geometry collection — stores pre-baked fragment layout.
 *
 * Workflow:
 *   1. Blender: Model mesh → Cell Fracture → N pieces with correct pivots
 *   2. Export FBX per piece (origin = object center)
 *   3. UE Import: N UStaticMesh assets
 *   4. Create this data asset, fill Fragments array
 *   5. Click "Generate Adjacency From Proximity" to auto-generate constraint links
 *
 * Reusable: same geometry can be shared across different object types
 * (different materials, break forces, fragment effects).
 */
UCLASS(BlueprintType)
class FATUMGAME_API UFlecsDestructibleGeometry : public UDataAsset
{
	GENERATED_BODY()

public:
	/** Fragment pieces with meshes and relative transforms */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fragments")
	TArray<FDestructibleFragment> Fragments;

	/** Adjacency graph — which fragments are neighbors (for constraint creation).
	 *  Auto-generated by GenerateAdjacencyFromProximity(). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Adjacency")
	TArray<FFragmentAdjacency> AdjacencyLinks;

	/** Max gap between fragment bounding boxes to be considered adjacent (cm) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Adjacency", meta = (ClampMin = "0.0"))
	float AdjacencyThreshold = 10.0f;

	/** Scale multiplier for auto-generated collider bounds (0-1 shrinks, >1 expands).
	 *  Applied during GenerateColliderBounds(), not at runtime. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Collider", meta = (ClampMin = "0.01"))
	float ColliderScale = 0.9f;

	int32 GetFragmentCount() const { return Fragments.Num(); }
	bool IsValid() const { return Fragments.Num() > 0; }

#if WITH_EDITOR
	/** Auto-generate AdjacencyLinks from Fragments based on proximity.
	 *  Uses bounding box extents + AdjacencyThreshold to determine neighbors. */
	UFUNCTION(CallInEditor, Category = "Utility")
	void GenerateAdjacencyFromProximity();

	/** Auto-generate ColliderHalfExtents for all fragments from mesh bounding boxes.
	 *  Applies ColliderScale multiplier. Overwrites existing values. */
	UFUNCTION(CallInEditor, Category = "Utility")
	void GenerateColliderBounds();
#endif
};
