// FlecsSaveEncoders_Transport — implementations + static-init registry hooks.
//
// CRITICAL: NetworkId on both FConnectorPlaced AND FPortSlot is saved as a plain
// integer but is REGENERATED on first sim tick post-load by NetworkRebuildSystem
// (which walks the snap-target graph and assigns canonical NetworkIds). The
// stored value persists only to keep the on-disk format symmetrical with the
// live struct — the regeneration on load makes its value moot.
//
// CRITICAL: FPortSlot is INLINE-ONLY inside FStationPorts.Ports[]. The Transport
// header forbids direct entity.set<FPortSlot>() (would crash 0x80000003 since the
// type isn't registered as a Flecs component). All FPortSlot serialization happens
// inside Encode_StationPorts as part of the variable-length array walk.

#include "Encoders/FlecsSaveEncoders_Transport.h"

#include "FlecsSaveComponentRegistry.h"
#include "FlecsSaveLog.h"
#include "FlecsSaveRemap.h"
#include "FlecsSaveTypeIds.h"

#include "FlecsTransportComponents.h"  // FConnectorPlaced, FStationPorts, FPortSlot,
                                       // FTagConnectorSegment, FTagConnectorPlaced
#include "FlecsCraftingTypes.h"        // EPortKind, EConnectorTransportRole

#include "Serialization/MemoryReader.h"
#include "Serialization/MemoryWriter.h"

#include "Encoders/FlecsSaveEncoderHelpers.h"   // SaveValue template — moved out of anonymous ns to fix unity-build collision

#include "flecs.h"

using FlecsSaveEnc::SaveValue;

// ═══════════════════════════════════════════════════════════════
// FConnectorPlaced  (TypeId 0x0703, Version 1)
//
// FrontSnapTargetId / BackSnapTargetId — REMAP each (0 = dangling/unsnapped).
// FrontSnappedToPortIndex / BackSnappedToPortIndex — 0..7 or 0xFF (dangling/peer).
// NetworkId — written but regenerated by NetworkRebuildSystem on first tick.
// ═══════════════════════════════════════════════════════════════

void FlecsSaveEncoders_Transport::Encode_ConnectorPlaced(const flecs::entity& E, TArray<uint8>& Out)
{
	const FConnectorPlaced* C = E.try_get<FConnectorPlaced>();
	checkf(C, TEXT("Encode_ConnectorPlaced: entity %llu lacks the component"),
		static_cast<uint64>(E.id()));

	FMemoryWriter Ar(Out, /*bIsPersistent=*/ true);
	Ar.SetIsSaving(true);

	SaveValue<uint16>(Ar, 1); // Version

	const uint32 FrontIdx = FlecsSaveRemap::EntityToSaveIndex(static_cast<flecs::entity_t>(C->FrontSnapTargetId));
	const uint32 BackIdx  = FlecsSaveRemap::EntityToSaveIndex(static_cast<flecs::entity_t>(C->BackSnapTargetId));
	SaveValue<uint32>(Ar, FrontIdx);
	SaveValue<uint32>(Ar, BackIdx);
	SaveValue<uint8>(Ar, C->FrontSnappedToPortIndex);
	SaveValue<uint8>(Ar, C->BackSnappedToPortIndex);
	SaveValue<uint32>(Ar, C->NetworkId);
}

bool FlecsSaveEncoders_Transport::Decode_ConnectorPlaced(const flecs::entity& E, const uint8* Bytes, uint32 Len)
{
	FMemoryReaderView Ar(TArrayView<const uint8>(Bytes, Len), /*bIsPersistent=*/ true);
	Ar.SetIsLoading(true);

	uint16 Version = 0; Ar << Version;
	if (Version != 1)
	{
		UE_LOG(LogFlecsSave, Error, TEXT("Decode_ConnectorPlaced: unknown version %u"), Version);
		return false;
	}

	uint32 FrontIdx = 0xFFFFFFFFu;
	uint32 BackIdx  = 0xFFFFFFFFu;
	uint8 FrontPort = 0xFF;
	uint8 BackPort  = 0xFF;
	uint32 NetworkId = 0;
	Ar << FrontIdx;
	Ar << BackIdx;
	Ar << FrontPort;
	Ar << BackPort;
	Ar << NetworkId;

	FConnectorPlaced C;
	C.FrontSnapTargetId       = static_cast<int64>(FlecsSaveRemap::ResolveSaveIndex(FrontIdx));
	C.BackSnapTargetId        = static_cast<int64>(FlecsSaveRemap::ResolveSaveIndex(BackIdx));
	C.FrontSnappedToPortIndex = FrontPort;
	C.BackSnappedToPortIndex  = BackPort;
	C.NetworkId               = NetworkId;
	// NetworkRebuildSystem will overwrite NetworkId on the first sim tick post-load.

	E.set<FConnectorPlaced>(C);
	return true;
}

// ═══════════════════════════════════════════════════════════════
// FStationPorts  (TypeId 0x0704, Version 1)
//
// Variable-length TArray<FPortSlot> with TInlineAllocator<8>. Per-port fields:
//   - Kind            (uint8 EPortKind)
//   - SocketName      (FName)
//   - ConnectedSegmentId (int64 REMAP; 0 = vacant)
//   - NetworkId       (uint8; regenerated post-load)
//   - AcceptPriority  (int8; design-time tunable)
//   - LocalOffsetCm   (FVector — full 24 bytes for designer-tunable port offset)
//
// PortCount upper bound is 8 (designer hard cap from FStationPorts allocator size).
// Encoder fails-fast above that to surface designer mistakes early.
// ═══════════════════════════════════════════════════════════════

void FlecsSaveEncoders_Transport::Encode_StationPorts(const flecs::entity& E, TArray<uint8>& Out)
{
	const FStationPorts* C = E.try_get<FStationPorts>();
	checkf(C, TEXT("Encode_StationPorts: entity %llu lacks the component"),
		static_cast<uint64>(E.id()));

	const int32 PortCount = C->Ports.Num();
	checkf(PortCount >= 0 && PortCount <= 8,
		TEXT("Encode_StationPorts: entity %llu has PortCount=%d outside [0, 8] designer cap"),
		static_cast<uint64>(E.id()), PortCount);

	FMemoryWriter Ar(Out, /*bIsPersistent=*/ true);
	Ar.SetIsSaving(true);

	SaveValue<uint16>(Ar, 1); // Version
	SaveValue<int32>(Ar, PortCount);

	for (const FPortSlot& Port : C->Ports)
	{
		SaveValue<uint8>(Ar, static_cast<uint8>(Port.Kind));

		FName SocketNameTmp = Port.SocketName;
		Ar << SocketNameTmp;

		const uint32 ConnIdx = FlecsSaveRemap::EntityToSaveIndex(static_cast<flecs::entity_t>(Port.ConnectedSegmentId));
		SaveValue<uint32>(Ar, ConnIdx);

		SaveValue<uint8>(Ar, Port.NetworkId);
		SaveValue<int8>(Ar, Port.AcceptPriority);

		// LocalOffsetCm — write as 3 floats (matches FVector serialization). Avoids
		// alignment quirks of binary-blob serialization across platforms.
		SaveValue<double>(Ar, Port.LocalOffsetCm.X);
		SaveValue<double>(Ar, Port.LocalOffsetCm.Y);
		SaveValue<double>(Ar, Port.LocalOffsetCm.Z);
	}
}

bool FlecsSaveEncoders_Transport::Decode_StationPorts(const flecs::entity& E, const uint8* Bytes, uint32 Len)
{
	FMemoryReaderView Ar(TArrayView<const uint8>(Bytes, Len), /*bIsPersistent=*/ true);
	Ar.SetIsLoading(true);

	uint16 Version = 0; Ar << Version;
	if (Version != 1)
	{
		UE_LOG(LogFlecsSave, Error, TEXT("Decode_StationPorts: unknown version %u"), Version);
		return false;
	}

	int32 PortCount = 0;
	Ar << PortCount;
	if (PortCount < 0 || PortCount > 8)
	{
		UE_LOG(LogFlecsSave, Error,
			TEXT("Decode_StationPorts: corrupt PortCount=%d (max 8 — designer cap)"), PortCount);
		return false;
	}

	FStationPorts C;
	C.Ports.Reserve(PortCount);

	for (int32 i = 0; i < PortCount; ++i)
	{
		FPortSlot Port;
		uint8 KindByte = 0;
		FName SocketName;
		uint32 ConnIdx = 0xFFFFFFFFu;
		uint8 NetworkId = 0;
		int8 AcceptPriority = 0;
		double OffsetX = 0.0;
		double OffsetY = 0.0;
		double OffsetZ = 0.0;
		Ar << KindByte;
		Ar << SocketName;
		Ar << ConnIdx;
		Ar << NetworkId;
		Ar << AcceptPriority;
		Ar << OffsetX;
		Ar << OffsetY;
		Ar << OffsetZ;

		Port.Kind                = static_cast<EPortKind>(KindByte);
		Port.SocketName          = SocketName;
		Port.ConnectedSegmentId  = static_cast<int64>(FlecsSaveRemap::ResolveSaveIndex(ConnIdx));
		Port.NetworkId           = NetworkId;
		Port.AcceptPriority      = AcceptPriority;
		Port.LocalOffsetCm       = FVector(OffsetX, OffsetY, OffsetZ);
		// NetworkRebuildSystem will overwrite NetworkId on the first sim tick post-load.

		C.Ports.Add(Port);
	}

	E.set<FStationPorts>(C);
	return true;
}

// ═══════════════════════════════════════════════════════════════
// AUTO-REGISTRATION
// ═══════════════════════════════════════════════════════════════

REGISTER_SAVE_COMPONENT(
	FlecsSaveTypeIds::kTypeId_ConnectorPlaced, FConnectorPlaced, 1,
	FlecsSaveEncoders_Transport::Encode_ConnectorPlaced,
	FlecsSaveEncoders_Transport::Decode_ConnectorPlaced)

REGISTER_SAVE_COMPONENT(
	FlecsSaveTypeIds::kTypeId_StationPorts, FStationPorts, 1,
	FlecsSaveEncoders_Transport::Encode_StationPorts,
	FlecsSaveEncoders_Transport::Decode_StationPorts)

REGISTER_SAVE_TAG(
	FlecsSaveTypeIds::kTypeId_TagConnectorSegment, FTagConnectorSegment)

REGISTER_SAVE_TAG(
	FlecsSaveTypeIds::kTypeId_TagConnectorPlaced, FTagConnectorPlaced)
