// FlecsSaveEncoders_Door — implementations + static-init registry hooks.

#include "Encoders/FlecsSaveEncoders_Door.h"

#include "FlecsSaveComponentRegistry.h"
#include "FlecsSaveLog.h"
#include "FlecsSaveRemap.h"
#include "FlecsSaveTypeIds.h"

#include "FlecsDoorComponents.h"
#include "FlecsGameTags.h"           // FTagDoor, FTagDoorTrigger
#include "FlecsBarrageComponents.h"  // FBarrageBody
#include "FlecsArtillerySubsystem.h" // SelfPtr / GetEntityForBarrageKey

#include "Serialization/MemoryReader.h"
#include "Serialization/MemoryWriter.h"

#include "Encoders/FlecsSaveEncoderHelpers.h"   // SaveValue template — moved out of anonymous ns to fix unity-build collision

#include "flecs.h"

using FlecsSaveEnc::SaveValue;

// ═══════════════════════════════════════════════════════════════
// FDoorInstance  (TypeId 0x0500, Version 1)
//
// FIELDS PERSISTED:
//   State, bUnlocked, bLastToggleState, AutoCloseTimer, TargetPosition, OpenDirection.
//
// FIELDS RESET ON LOAD:
//   ConstraintKey = 0  — regenerated by DoorSystem on first tick post-load using
//                        FDoorStatic params + the new Barrage body.
// ═══════════════════════════════════════════════════════════════

void FlecsSaveEncoders_Door::Encode_DoorInstance(const flecs::entity& E, TArray<uint8>& Out)
{
	const FDoorInstance* C = E.try_get<FDoorInstance>();
	checkf(C, TEXT("Encode_DoorInstance: entity %llu lacks the component"),
		static_cast<uint64>(E.id()));

	FMemoryWriter Ar(Out, /*bIsPersistent=*/ true);
	Ar.SetIsSaving(true);

	SaveValue<uint16>(Ar, 1); // Version
	SaveValue<uint8>(Ar, static_cast<uint8>(C->State));
	SaveValue<uint8>(Ar, C->bUnlocked        ? 1u : 0u);
	SaveValue<uint8>(Ar, C->bLastToggleState ? 1u : 0u);
	SaveValue<float>(Ar, C->AutoCloseTimer);
	SaveValue<float>(Ar, C->TargetPosition);
	SaveValue<int8>(Ar, C->OpenDirection);
	// ConstraintKey intentionally NOT serialized — regenerated post-load by DoorSystem.
}

bool FlecsSaveEncoders_Door::Decode_DoorInstance(const flecs::entity& E, const uint8* Bytes, uint32 Len)
{
	FMemoryReaderView Ar(TArrayView<const uint8>(Bytes, Len), /*bIsPersistent=*/ true);
	Ar.SetIsLoading(true);

	uint16 Version = 0; Ar << Version;
	if (Version != 1)
	{
		UE_LOG(LogFlecsSave, Error, TEXT("Decode_DoorInstance: unknown version %u"), Version);
		return false;
	}

	FDoorInstance C;
	uint8 StateByte = 0;
	uint8 UnlockedByte = 0;
	uint8 ToggleByte = 0;
	Ar << StateByte;
	Ar << UnlockedByte;
	Ar << ToggleByte;
	Ar << C.AutoCloseTimer;
	Ar << C.TargetPosition;
	Ar << C.OpenDirection;

	C.State            = static_cast<EDoorState>(StateByte);
	C.bUnlocked        = (UnlockedByte != 0);
	C.bLastToggleState = (ToggleByte   != 0);
	C.ConstraintKey    = 0;  // regenerated by DoorSystem post-load (FDoorStatic + new body)

	E.set<FDoorInstance>(C);
	return true;
}

// ═══════════════════════════════════════════════════════════════
// FDoorTriggerLink  (TypeId 0x0501, Version 1)
//
// TargetDoorKey is the door's BarrageKey (uint64 in the live struct). We persist the
// door entity's SaveIndex (REMAP) instead so the link survives the BarrageKey churn
// across save/load. Decoder leaves TargetDoorKey = 0 — a post-decode pass resolves
// each link by looking up the new door entity's FBarrageBody.BarrageKey.
//
// In Phase 5 the post-decode resolve runs inside the same sim-thread rebind step that
// re-creates Barrage bodies; for now we store the resolved entity_t in a transient
// member during decode and the rebind helper consults the REMAP table itself.
// ═══════════════════════════════════════════════════════════════

void FlecsSaveEncoders_Door::Encode_DoorTriggerLink(const flecs::entity& E, TArray<uint8>& Out)
{
	const FDoorTriggerLink* C = E.try_get<FDoorTriggerLink>();
	checkf(C, TEXT("Encode_DoorTriggerLink: entity %llu lacks the component"),
		static_cast<uint64>(E.id()));

	FMemoryWriter Ar(Out, /*bIsPersistent=*/ true);
	Ar.SetIsSaving(true);

	SaveValue<uint16>(Ar, 1); // Version

	// Resolve TargetDoorKey (BarrageKey/SkeletonKey, stored as uint64) to the door entity
	// via reverse lookup, then to that entity's SaveIndex via the writer's reverse map.
	// On load the decoder leaves TargetDoorKey=0; a post-decode pass uses the SaveIndex
	// to look up the new door entity and its fresh BarrageKey.
	uint32 DoorSaveIdx = 0xFFFFFFFFu;
	if (C->TargetDoorKey != 0)
	{
		// Sim-thread reverse: BarrageKey -> Flecs entity.
		// This encoder runs on the sim thread inside the save snapshot fence.
		if (UFlecsArtillerySubsystem* Artillery = UFlecsArtillerySubsystem::SelfPtr)
		{
			const FSkeletonKey BarrageKey(C->TargetDoorKey);
			const flecs::entity DoorEntity = Artillery->GetEntityForBarrageKey(BarrageKey);
			if (DoorEntity.is_valid())
			{
				DoorSaveIdx = FlecsSaveRemap::EntityToSaveIndex(DoorEntity.id());
			}
			else
			{
				UE_LOG(LogFlecsSave, Warning,
					TEXT("Encode_DoorTriggerLink: trigger %llu links to BarrageKey=%llu with no live entity — dropping link"),
					static_cast<uint64>(E.id()), C->TargetDoorKey);
			}
		}
	}
	SaveValue<uint32>(Ar, DoorSaveIdx);
}

bool FlecsSaveEncoders_Door::Decode_DoorTriggerLink(const flecs::entity& E, const uint8* Bytes, uint32 Len)
{
	FMemoryReaderView Ar(TArrayView<const uint8>(Bytes, Len), /*bIsPersistent=*/ true);
	Ar.SetIsLoading(true);

	uint16 Version = 0; Ar << Version;
	if (Version != 1)
	{
		UE_LOG(LogFlecsSave, Error, TEXT("Decode_DoorTriggerLink: unknown version %u"), Version);
		return false;
	}

	uint32 DoorSaveIdx = 0xFFFFFFFFu;
	Ar << DoorSaveIdx;

	FDoorTriggerLink C;
	C.TargetDoorKey = 0;  // resolved by post-decode rebind pass.

	if (DoorSaveIdx != 0xFFFFFFFFu)
	{
		const flecs::entity_t DoorEntityId = FlecsSaveRemap::ResolveSaveIndex(DoorSaveIdx);
		if (DoorEntityId != 0 && UFlecsArtillerySubsystem::SelfPtr)
		{
			flecs::world* World = UFlecsArtillerySubsystem::SelfPtr->GetFlecsWorld();
			if (World)
			{
				flecs::entity DoorEntity(*World, DoorEntityId);
				if (DoorEntity.is_alive())
				{
					if (const FBarrageBody* Body = DoorEntity.try_get<FBarrageBody>())
					{
						C.TargetDoorKey = static_cast<uint64>(Body->BarrageKey);
					}
					else
					{
						// Door entity exists but Barrage body hasn't been restored yet —
						// the body-restore pass runs AFTER the component-decode pass, so
						// this path can happen on intermediate component-decode order.
						// Log + leave 0; the rebind pass will fix it up.
						UE_LOG(LogFlecsSave, Verbose,
							TEXT("Decode_DoorTriggerLink: door entity %llu has no FBarrageBody yet — TargetDoorKey deferred"),
							DoorEntityId);
					}
				}
			}
		}
	}

	E.set<FDoorTriggerLink>(C);
	return true;
}

// ═══════════════════════════════════════════════════════════════
// AUTO-REGISTRATION
// ═══════════════════════════════════════════════════════════════

REGISTER_SAVE_COMPONENT(
	FlecsSaveTypeIds::kTypeId_DoorInstance, FDoorInstance, 1,
	FlecsSaveEncoders_Door::Encode_DoorInstance,
	FlecsSaveEncoders_Door::Decode_DoorInstance)

REGISTER_SAVE_COMPONENT(
	FlecsSaveTypeIds::kTypeId_DoorTriggerLink, FDoorTriggerLink, 1,
	FlecsSaveEncoders_Door::Encode_DoorTriggerLink,
	FlecsSaveEncoders_Door::Decode_DoorTriggerLink)

REGISTER_SAVE_TAG(
	FlecsSaveTypeIds::kTypeId_TagDoor, FTagDoor)

REGISTER_SAVE_TAG(
	FlecsSaveTypeIds::kTypeId_TagDoorTrigger, FTagDoorTrigger)
