//CC NA R

#pragma once

#include "NativeGameplayTags.h"

	SKELETONKEY_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	SKELETONKEY_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	SKELETONKEY_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	SKELETONKEY_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);

	SKELETONKEY_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	SKELETONKEY_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	SKELETONKEY_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	SKELETONKEY_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	SKELETONKEY_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	SKELETONKEY_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);
